dist: xenial
language: java
branches:
  only:
  - master
  - /^\d+\.\d+$/
before_install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        wget --no-check-certificate https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip
        wget --no-check-certificate https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip
        /C/Progra~1/7-Zip/7z.exe x apache-maven-3.6.3-bin.zip -o/c/mvn363
        /C/Progra~1/7-Zip/7z.exe x openjdk-11.0.2_windows-x64_bin.zip -o/c/java
        ;;
    esac
before_script:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        export "JAVA_HOME=/c/java/jdk-11.0.2"
        export "PATH=$JAVA_HOME/bin:$PATH"
        export "PATH=$JAVA_HOME/jre/bin:$PATH"
        export "MAVEN_HOME=/c/mvn363/apache-maven-3.6.3"
        export "M2_HOME=/c/mvn363/apache-maven-3.6.3"
        export "PATH=/c/mvn363/apache-maven-3.6.3/bin:$PATH"
        ;;
      *)
        sudo apt-get update -qq
        sudo apt-get install --only-upgrade openjdk-8-jdk
        ;;
    esac
jobs:
  include:
    - stage: test
      name: "OpenJDK 8"
      os: linux
      jdk: openjdk8
      script: ./gradlew build
    - stage: test
      name: "OpenJDK 11"
      os: windows
      language: shell
      script: .\gradlew build
